name: "Release"

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: "🚀 Release"
    runs-on: ubuntu-20.04
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2
      - name: "🏷️ Get version tag"
        id: get-version
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
      - name: "✏️ Generate changelog"
        id: generate-changelog
        if: runner.os == 'Linux'
        uses: heinrichreimer/action-github-changelog-generator@v2.2
        with:
          onlyLastTag: "true"
          stripHeaders: "true"
          stripGeneratorNotice: "true"
      - name: "📤 Upload changelog"
        uses: actions/upload-artifact@v2
        with:
          path: ./CHANGELOG.md
          name: Changelog
      - name: "🚀 Create GitHub release"
        id: create-github-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get-version.outputs.tag }}
          body: ${{ steps.generate-changelog.outputs.changelog }}
          prerelease: false
